**Unary ufunc (Universal Functions)**
If you want to update the original array, while calling function, also pass original array as second parameter
Example: np.sqrt(arr,arr) --> will modify te original array too

In [2]:
import numpy as np

In [8]:
#1. abs, fabs: fabs always return floating point value
x = np.array([-1, 1, 2, -3])
temp = np.abs(x)
temp

array([1, 1, 2, 3])

In [9]:
#2. sqrt
np.sqrt(temp)           #sqrt for -ve values give error and corresponding value becomes nan

array([1.        , 1.        , 1.41421356, 1.73205081])

In [10]:
#3. square
y = np.array([1, 2, 3, 4])
np.square(y)

array([ 1,  4,  9, 16], dtype=int32)

In [11]:
#4. exp
np.exp(y)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [15]:
#5. log, log10, log2, log1p
print(np.log(y))
print(np.log10(y))
print(np.log2(y))
print(np.log1p(y))

[0.         0.69314718 1.09861229 1.38629436]
[0.         0.30103    0.47712125 0.60205999]
[0.        1.        1.5849625 2.       ]
[0.69314718 1.09861229 1.38629436 1.60943791]


In [16]:
#6. sign
np.sign(x)   #original array [-1,1,2,-3], so it replaces -ve no. with -1 & +ve no. with +1

array([-1,  1,  1, -1])

In [18]:
#7. ceil, floor, rint
z = np.array([1.3, 2.5, 3.8, 4.2])
print(np.ceil(z))
print(np.floor(z))
print(np.rint(z)) 

[2. 3. 4. 5.]
[1. 2. 3. 4.]
[1. 2. 4. 4.]


In [19]:
#8. modf. Returns 2 arrays as output, first is remainder and second is whole_part
np.modf(z)
#can also write: remainder, whole_part = np.modf(z)

(array([0.3, 0.5, 0.8, 0.2]), array([1., 2., 3., 4.]))

In [24]:
#9. isnan, isfinite, isinf
import math
arr = np.array([float('NaN'), 1, math.pi, float('inf'), math.inf])
print(arr)
print(np.isnan(arr))
print(np.isfinite(arr))
print(np.isinf(arr))
#showing math.pi as finite!
#also, nan is neither finite nor infinite

[       nan 1.         3.14159265        inf        inf]
[ True False False False False]
[False  True  True False False]
[False False False  True  True]


In [31]:
#10: Regular & Hyperbolic trignometic functions: cos, cosh, sin, sinh, tan, tanh
print(np.sin(y))
print(np.sinh(y))

print(np.cos(y))
print(np.cosh(y))

print(np.tan(y))
print(np.tanh(y))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 1.17520119  3.62686041 10.01787493 27.2899172 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.54308063  3.76219569 10.067662   27.30823284]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]
[0.76159416 0.96402758 0.99505475 0.9993293 ]


In [34]:
#11: Inverse trignometic functions: arccos. arccosh, arcsin, arcsinh, arctan, arctanh

print(np.arcsin([1,-1]))
print(np.arcsinh([1,-1]))

print(np.arccos([1,-1]))
print(np.arccosh([1,-1]))

print(np.arctan([1,-1]))
print(np.arctanh([1,-1]))


[ 1.57079633 -1.57079633]
[ 0.88137359 -0.88137359]
[0.         3.14159265]
[ 0. nan]
[ 0.78539816 -0.78539816]
[ inf -inf]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in arccosh
  import sys
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: divide by zero encountered in arctanh
  # Remove the CWD from sys.path while we load stuff.


In [29]:
#12: Logical_not 
print(x)
print(np.logical_not(x<0))


[-1  1  2 -3]
[False  True  True False]


**Binary ufunc**

In [35]:
#1. add, subtract

print(np.add(x,y))
print(np.subtract(x,y))


[0 3 5 1]
[-2 -1 -1 -7]


In [36]:
#2. multiply, divide, floor_divide

print(np.multiply(x,y))
print(np.divide(x,y))
print(np.floor_divide(x,y)) #will automatically adjust value to best type


[ -1   2   6 -12]
[-1.          0.5         0.66666667 -0.75      ]
[-1  0  0 -1]


In [37]:
#3. power
print(np.power(x,y))

[-1  1  8 81]


In [38]:
#4. maximum, fmax, minimum, fmin. fmax & fmin ignores nan

print(np.maximum(x,y))
print(np.minimum(x,y))


[1 2 3 4]
[-1  1  2 -3]


In [43]:
#5. mod
np.mod(np.array([4,6]),np.array([2,3]))


array([0, 0], dtype=int32)

In [44]:
#6. copysign
np.copysign(np.array([4,6]),np.array([-2,-3]))


array([-4., -6.])

In [56]:
#7. greater, greater_equal, less, less_equal, equal, not_equal

ar1= np.array([1,6,3])
ar2= np.array([5,6,1])

print(np.greater(ar1,ar2))
print(np.less(ar1,ar2))
print(np.less_equal(ar1,ar2))
print(np.equal(ar1,ar2))
print(np.not_equal(ar1,ar2))


[False False  True]
[ True False False]
[ True  True False]
[False  True False]
[ True False  True]


In [51]:
#8. logical_and, logical_or, logical_xor

print(np.logical_and([0,1],[1,0]))
print(np.logical_or([0,1],[1,0]))
print(np.logical_xor([1,1],[1,0]))


[False False]
[ True  True]
[False  True]
