**Advance Numpy**

1. stride: a tuple of integer numbers each of which indicate bytes for a particular dimension. It tells how many bytes to jump in data buffer.
2. dtypes have super types like np.integer, np.floating

                                          generic
                                 ___________________________      
                                 /      /         \        \
                            number     character   bool_   object_
                          /      \       /     \
                    integer   inexact  string_  unicode_    
                    /  \        /   \
              unsigned signed  float complex  
              
3. Advance array manipulations
    - reshape((2,4),order='C') 'C' means row major, 'F' means column major
    - flattening/raveling means converting array into 1d. ravel returns a view only whereas flatten returns a copy. Modifying values in view returned by ravel will effect original array. You can pass 'C' or 'F' as argument too.
     
4. Concatinating/Splitting arrays:
    - concatenate: [pass list of arrays], axis=0 or 1
    - vstack/row_stack: stack array row-wise (along axis=0)
    - hstack: stack array column-wise (along axis=1)
    - column_stack: like hstack but first it will convert a 1d array into 2d
    - dstack: stack along depth (along axis=2)
    - split: split array at a passed location along the mentioned axis
    - hsplit, vsplit: split along axis=0 and axis=1 respectively
    - Using r_ and c_ namespaces?
    
5. tile and repeat: tile is like stacking whereas repeat works on every element. For 1d array, you cannot repeat or tile along axis=1. 

6. Fancy Indexing: put and take to set or get a value on given index

7. Broadcasting: 


In [1]:
import numpy as np

In [4]:
#stride
arr = np.arange(1,10).reshape(3,3)
print(arr.itemsize) #byte used to store a single value
print(arr.strides)

4
(12, 4)


In [7]:
#checking dtype super class
print(np.issubdtype(arr.dtype, np.integer))
print(np.issubdtype(arr.dtype, np.floating))

True
False


In [8]:
#to check all parent classes of specific dtype
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [9]:
arr[::-1]  #:: means select all, -1 means backward

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [11]:
print(arr)
print(arr[:, -1]) #all rows last column

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6 9]


In [18]:
x = np.arange(12)
print(x)
print(x.reshape(4,3))
print(x.reshape(4,3).reshape(3,4))

print(x.reshape(6, -1)) #-1 means column will be decided accordingly

#you can pass other array shape like this: x.reshape(y.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [20]:
y = np.arange(15).reshape(5,3)
print(y)
print(y.flatten())

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [22]:
print(y.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [25]:
#concatenate/stacking
arr1 = np.arange(1,7,1).reshape(2,3)
arr2 = np.arange(7,13,1).reshape(2,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [26]:
np.concatenate([arr1,arr2],axis=0)  #same result with np.vstack([arr1,arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
np.concatenate([arr1,arr2],axis=1)  #same result with np.hstack([arr1,arr2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [32]:
np.dstack([arr1,arr2])  

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [34]:
np.split(arr,[1])  #splitted after first row


[array([[1, 2, 3]]), array([[4, 5, 6],
        [7, 8, 9]])]

In [35]:
np.hsplit(arr,[1])

[array([[1],
        [4],
        [7]]), array([[2, 3],
        [5, 6],
        [8, 9]])]

In [36]:
np.vsplit(arr,[1])

[array([[1, 2, 3]]), array([[4, 5, 6],
        [7, 8, 9]])]

In [37]:
z = np.array([1,2])
np.repeat(z,2)        #z.repeat(2), same result: z.repeat(2, axis=0)

array([1, 1, 2, 2])

In [38]:
np.tile(z,2)          #z.tile(2) 

array([1, 2, 1, 2])

In [44]:
a = np.arange(10)*100
print(a)

[  0 100 200 300 400 500 600 700 800 900]


In [45]:
ind = [1,5]
print(a[ind])

[100 500]


In [47]:
a.put(ind, 1)
a.take(ind)

array([1, 1])