**Importing Numpy**

In [1]:
import numpy as np  

**Creating Numpy Arrays**


In [13]:
arr1d = np.array([1, 2, 3 , 4])     #1D array, can pass list too
arr2d = np.array([[1,2],[3,4]])     #2D array, can pass list too

In [14]:
d1 = np.arange(10)                  #0-9 1D array
d2 = np.arange(10).reshape((2,5))   #0-9 2D array, rows & columns should be given accordingly
d3 = np.arange(0,10,1, dtype=np.int64) # can given start, end and step, end will not be included

In [15]:
r1 = np.random.randn(2)             #random numbers, 2 elements numpy array
r2 = np.random.randn(2,2)           # 2*2 numpy array of random numbers

In [16]:
n1 = np.ones(5)                    
n2 = np.zeros(5)
n3 = np.empty(5)                    #might return zero or garbage values

print(n1)
print(n2)
print(n3)

#you can reshape any numpy array different dimensions as long as given dimensions are valid


[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]


In [26]:
i1 = np.identity(2)               #identity matrix of n*n with 1's in diagonal and zeros elsewhere.
i1

array([[1., 0.],
       [0., 1.]])

In [ ]:
#other numpy functions:

#np.asarray: when you don't want to copy if input is already a numpy array
#ones_like: takes an array and uses its dimensions/shape to produces another array of ones
#zeros_like: takes an array and uses its dimensions/shape to produces another array of zeros
#empty_like: same like empty, both are used to allocate memory
#full & full_like: use it if you want to specify a value with which numpy array should be filled
#np.eye: same like np.identity

**Checking Shape & Type of a ndarray**

In [17]:
print(arr2d.shape)                  #how many rows/columns
print(arr2d.dtype)                  #default datatype :float64, you can explicilty assign type while creating a numpy array
print(arr2d.ndim)                   #dimensions

print(d1.shape)
print(d1.dtype)                  
print(d1.ndim)

(2, 2)
int32
2
(10,)
int32
1


In [19]:
n4 = np.ones((2,3,2), dtype=np.int32)
print(n4)
print(n4.shape)
print(n4.dtype)                  
print(n4.ndim)


[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]
(2, 3, 2)
int32
3


**Numpy Datatypes and Changing typing**
#signed int: int8, int16, int32, int64
#usigned int: uint8, uint16, uint32, uint64
#float: float16, float32, float64, float128
#complex: complex64, complex128, complex, 256
#bool: True/False
#string_, object, unicode_

#you can use typecodes (should be places inside quotes) too (book 91-Table 4.2)

In [27]:
n4 = n4.astype(np.float32)
n4


array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]], dtype=float32)

In [28]:
arr2d = arr2d.astype(n4.dtype)          #can also give type of another array
arr2d

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [31]:
#if you convert float to int, decimal part is truncated
#string to float: if string contains alphabets, error generated 
test = np.array(['6','5','-1.2'],dtype=np.string_)
print(test)
test = test.astype(np.float32)
print(test)

[b'6' b'5' b'-1.2']
[ 6.   5.  -1.2]


**Arithmetic with numpy Arrays**
+,-,*, 1/narray, ** (exponent), a > b, a < b, a == b, a!=b
Certain operations generate error if dimensions mismatch.
Operation between different sized arrays is called Broadcasting

In [34]:
a1 = np.array([1,2,3,4])
a2 = np.array([6,7,8,9])

print(a1+a2)
print(a2-a1)
print(1/a1)
print(a1**2)
print(a1>a2)
print(a1<a2)
print(a1==a2)
print(a1!=a2)

[ 7  9 11 13]
[5 5 5 5]
[1.         0.5        0.33333333 0.25      ]
[ 1  4  9 16]
[False False False False]
[ True  True  True  True]
[False False False False]
[ True  True  True  True]


**Indexing & Slicing**

Term: rows/columns OR axis0/axis1

For 1d numpy array:
1. start:end --- end not included. E.g. arr[5:8] means element at position 5 to 7, you can get/set value (View)
2. [:] -- to get all values
3. to get a copy you can write arr[5:8].copy()

For 2d array:
4. arr2d[0][2] or you can write arr2d[0,2]

Boolean Indexing:
5. you can a condition inside [] to get repective values
Example:
data[data>0]
data[data<0]
data[data==0]
data[data!=0]
data[(data>2) & (data<5)]
Remember for multiple conditions, brackets must be placed. Also, for boolean indexing, & operator cannot be replaced by 'and'.

6. If you write data>2 only: you will get resultant array as True/False
7. Negative indices selects from backward.
8. Fancy Indexing: specify the column no. inside [] to get the desired rows in a particular order
9. Slicing/Indexing works on orignal array whereas fancy indexing gives copy of array

In [36]:
arr2d[:1]                                  

array([[1., 2.]], dtype=float32)

In [37]:
arr2d[:1,:1]

array([[1.]], dtype=float32)

In [52]:
#Boolean Indexing Example:
names = np.array(['Bob', 'Joe','Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.arange(0,28).reshape(7,4)
print(names)
print(data)


['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]


In [53]:
cond = names == 'Bob'
data[cond]                     #alternate: data[names == 'Bob']

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [54]:
#so it returns entire row corresponding the satisfied condition 
data[~(cond)]                 #alternate: data[names != 'Bob']

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [58]:
#you can choose column too
data[~(cond),:2]   

array([[ 4,  5],
       [ 8,  9],
       [16, 17],
       [20, 21],
       [24, 25]])

In [56]:
#if condition applied on same array, it returns True/False
names[names=='Bob']

array(['Bob', 'Bob'], dtype='<U4')

In [57]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [60]:
mask = (names=='Bob') | (names=='Will')
data[mask]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [61]:
mask2 = (names=='Bob') & (names=='Will')
data[mask2]

array([], shape=(0, 4), dtype=int32)

In [62]:
#Fancy indexing:
data[[1,3,4]]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [63]:
data[[1,3,4],[1,0,3]]       #selective rows, from each row selective column     

array([ 5, 12, 19])

In [66]:
data[[1,3,4]][:,[1,0,3,2]]  #no comma in b/w, 

array([[ 5,  4,  7,  6],
       [13, 12, 15, 14],
       [17, 16, 19, 18]])

In [67]:
#swap_axes: to swap mentioned axes, returns a view not a copy
data.swapaxes(0,1)  #original shape:(7,4), after swap it becomes (4,7)


array([[ 0,  4,  8, 12, 16, 20, 24],
       [ 1,  5,  9, 13, 17, 21, 25],
       [ 2,  6, 10, 14, 18, 22, 26],
       [ 3,  7, 11, 15, 19, 23, 27]])

In [68]:
data.T            #swap all axes

array([[ 0,  4,  8, 12, 16, 20, 24],
       [ 1,  5,  9, 13, 17, 21, 25],
       [ 2,  6, 10, 14, 18, 22, 26],
       [ 3,  7, 11, 15, 19, 23, 27]])

In [74]:
data.transpose()

array([[ 0,  4,  8, 12, 16, 20, 24],
       [ 1,  5,  9, 13, 17, 21, 25],
       [ 2,  6, 10, 14, 18, 22, 26],
       [ 3,  7, 11, 15, 19, 23, 27]])

In [77]:
data.transpose((0,1))    #0 & 1 means axes

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [78]:
data.transpose((1,0)) 

array([[ 0,  4,  8, 12, 16, 20, 24],
       [ 1,  5,  9, 13, 17, 21, 25],
       [ 2,  6, 10, 14, 18, 22, 26],
       [ 3,  7, 11, 15, 19, 23, 27]])

In [69]:
#dot product
np.dot(data.T, data)  

array([[1456, 1540, 1624, 1708],
       [1540, 1631, 1722, 1813],
       [1624, 1722, 1820, 1918],
       [1708, 1813, 1918, 2023]])

In [70]:
np.dot(data, data.T)

array([[  14,   38,   62,   86,  110,  134,  158],
       [  38,  126,  214,  302,  390,  478,  566],
       [  62,  214,  366,  518,  670,  822,  974],
       [  86,  302,  518,  734,  950, 1166, 1382],
       [ 110,  390,  670,  950, 1230, 1510, 1790],
       [ 134,  478,  822, 1166, 1510, 1854, 2198],
       [ 158,  566,  974, 1382, 1790, 2198, 2606]])